@baseUrl = https://uw464ok72fw5a4yw55pxmg2hrq0lpxlv.lambda-url.eu-west-3.on.aws
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiQURNSU4iLCJ1c2VySWQiOiI1NTU1NTU1NS01NTU1LTU1NTUtNTU1NS01NTU1NTU1NTU1MDUiLCJzdWIiOiJmYXJhLnJhc29sb0BzY2hvb2wubWciLCJpYXQiOjE3ODcxNzIxNTIsImV4cCI6MTc4NzE3NTc1Mn0.MV7Ly7-YGAnR_4eVGuFR77bztvjs4hKw_AXi5zauSQmOIhdmqE6oaMrD9osULEwev51wU5AePjS46WI0p1DecQ
@roxannId = 1af9dcf2-014a-4adf-a670-a28ac2e3d8c6

### Login admin
POST https://uw464ok72fw5a4yw55pxmg2hrq0lpxlv.lambda-url.eu-west-3.on.aws/auth/login
Content-Type: application/json

{
  "email": "fara.rasolo@school.mg",
  "password": "password123"
}

### Login student Roxann
POST https://uw464ok72fw5a4yw55pxmg2hrq0lpxlv.lambda-url.eu-west-3.on.aws/auth/login
Content-Type: application/json

{
  "email": "hei.roxann@gmail.com",
  "password": "password123"
}

### Déclencher la génération du relevé pour Roxann
POST https://uw464ok72fw5a4yw55pxmg2hrq0lpxlv.lambda-url.eu-west-3.on.aws/students/1af9dcf2-014a-4adf-a670-a28ac2e3d8c6/releve-pdf
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiQURNSU4iLCJ1c2VySWQiOiI1NTU1NTU1NS01NTU1LTU1NTUtNTU1NS01NTU1NTU1NTU1MDUiLCJzdWIiOiJmYXJhLnJhc29sb0BzY2hvb2wubWciLCJpYXQiOjE3ODcyMDMzMzgsImV4cCI6MTc4NzIwNjkzOH0.SWMFUQRe9NL2P8IvFg8yX2l5IhMd_qsNCCU4_abFpMUhrYaSa_VBkD7Cs4t4AlvNTf4MjrykFWlIs3pWzqQ3Mg